version: "3.8"

services:

  backend:
    build:
      context: .
      target: base
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/var/www/html:rw
      - ./frontend/dist:/var/www/html/dist/:rw
    ports:
      - 3001:80